// controllers/triviacontroller.js
const getQuestions = (req, res) => {
  const questions = [
      {
              question: "¿Qué vitamina es esencial para la salud ósea?",
                      options: ["Vitamina A", "Vitamina B12", "Vitamina C", "Vitamina D"],
                              answer: "Vitamina D"
                                  },
                                      {
                                              question: "¿Cuál es la fuente principal de energía para el cuerpo?",
                                                      options: ["Proteínas", "Carbohidratos", "Grasas", "Fibra"],
                                                              answer: "Carbohidratos"
                                                                  },
                                                                      {
                                                                              question: "¿Cuál es la función principal de las proteínas?",
                                                                                      options: ["Suministrar energía", "Reparar tejidos", "Aumentar grasas", "Aumentar la sed"],
                                                                                              answer: "Reparar tejidos"
                                                                                                  },
                                                                                                      {
                                                                                                              question: "¿Cuál de los siguientes es un antioxidante natural?",
                                                                                                                      options: ["Vitamina K", "Vitamina C", "Calcio", "Hierro"],
                                                                                                                              answer: "Vitamina C"
                                                                                                                                  },
                                                                                                                                      {
                                                                                                                                              question: "¿Cuál es el mineral más abundante en el cuerpo humano?",
                                                                                                                                                      options: ["Hierro", "Magnesio", "Calcio", "Potasio"],
                                                                                                                                                              answer: "Calcio"
                                                                                                                                                                  },
                                                                                                                                                                      {
                                                                                                                                                                              question: "¿Cuál de los siguientes es una fuente rica en ácidos grasos omega-3?",
                                                                                                                                                                                      options: ["Plátano", "Aguacate", "Salmón", "Espinacas"],
                                                                                                                                                                                              answer: "Salmón"
                                                                                                                                                                                                  },
                                                                                                                                                                                                      {
                                                                                                                                                                                                              question: "¿Qué tipo de grasas son saludables y recomendadas en la dieta?",
                                                                                                                                                                                                                      options: ["Grasas saturadas", "Grasas trans", "Grasas insaturadas", "Grasas hidrogenadas"],
                                                                                                                                                                                                                              answer: "Grasas insaturadas"
                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                              question: "¿Cuál es la principal función de la fibra en la dieta?",
                                                                                                                                                                                                                                                      options: ["Proporcionar energía", "Regular el tránsito intestinal", "Aumentar el azúcar en sangre", "Incrementar la masa muscular"],
                                                                                                                                                                                                                                                              answer: "Regular el tránsito intestinal"
                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                              question: "¿Cuál de estos alimentos es una buena fuente de hierro?",
                                                                                                                                                                                                                                                                                      options: ["Manzana", "Lechuga", "Lentejas", "Arroz"],
                                                                                                                                                                                                                                                                                              answer: "Lentejas"
                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                              question: "¿Qué mineral es necesario para la formación de hemoglobina?",
                                                                                                                                                                                                                                                                                                                      options: ["Potasio", "Sodio", "Hierro", "Cobre"],
                                                                                                                                                                                                                                                                                                                              answer: "Hierro"
                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                              question: "¿Qué vitamina ayuda a la absorción del hierro en el cuerpo?",
                                                                                                                                                                                                                                                                                                                                                      options: ["Vitamina A", "Vitamina B12", "Vitamina C", "Vitamina D"],
                                                                                                                                                                                                                                                                                                                                                              answer: "Vitamina C"
                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                              question: "¿Cuál de los siguientes alimentos es rico en vitamina A?",
                                                                                                                                                                                                                                                                                                                                                                                      options: ["Zanahorias", "Manzanas", "Panes", "Papas"],
                                                                                                                                                                                                                                                                                                                                                                                              answer: "Zanahorias"
                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Cuál es el macronutriente más abundante en el huevo?",
                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Carbohidratos", "Grasas", "Proteínas", "Fibra"],
                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Proteínas"
                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Cuál de estos alimentos es una buena fuente de calcio?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Leche", "Carne", "Naranja", "Café"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Leche"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Qué vitamina es sintetizada por el cuerpo cuando se expone al sol?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina K"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Vitamina D"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Cuál es el efecto del consumo excesivo de azúcar?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Aumenta el peso corporal", "Mejora la visión", "Reduce el estrés", "Aumenta la masa muscular"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Aumenta el peso corporal"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Cuál de los siguientes es un alimento probiótico?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Yogur", "Carne", "Pan integral", "Cereal"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Yogur"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Cuál es el principal beneficio del consumo de agua?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Proporciona energía", "Mantiene la hidratación", "Aumenta la masa muscular", "Reduce la fatiga"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Mantiene la hidratación"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Qué nutriente es fundamental para el desarrollo del cerebro en los niños?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Hierro", "Ácido fólico", "Zinc", "Vitamina B12"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Ácido fólico"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "¿Qué fruta es conocida por su alto contenido en potasio?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options: ["Naranja", "Banana", "Manzana", "Uva"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answer: "Banana"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.json({ questions });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      module.exports = { getQuestions };